export const GET_WRITEABLE_JOURNAL_REQUEST = 'GET_WRITEABLE_JOURNAL_REQUEST'
export const GET_WRITEABLE_JOURNAL_SUCCESS = 'GET_WRITEABLE_JOURNAL_SUCCESS'
export const GET_WRITEABLE_JOURNAL_FAIL = 'GET_WRITEABLE_JOURNAL_FAIL'
export const GET_WRITEABLE_JOURNAL_RESET = 'GET_WRITEABLE_JOURNAL_RESET'

